#注册中心配置  
service:  
  register:
    center:
      ip: 127.0.0.1
      hostname: peer1
      port: 19081
    center2: 
      ip: 127.0.0.1
      hostname: peer2
      port: 19082
eureka:
  client:
    serviceUrl: 
      defaultZone: http://${service.register.center.hostname}:${service.register.center.port}/eureka/
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 5000             
#数据库配置
db: 
  host: 127.0.0.1
  port: 3306
  name: ifirstaid_encode_dev
  
spring:
  datasource:
    username: root
    password: 
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true
#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml