spring:
  profiles:
    active: peer1
  application:
    name: alpha-server-discovery
---
spring:
  profiles: peer1
server:
  port: 19081
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: false #是否将自已注册为客户端
    fetch-registry: false
    #serviceUrl: 
    #  defaultZone: http://peer2:19082/eureka/ 
  server:
    enable-self-preservation: false #自我保护模式,默认为开启
    eviction-interval-timer-in-ms: 5000 #扫描失效服务的时间间隔,默认60秒
---
spring:
  profiles: peer2
server:
  port: 19082
eureka:
  instance:
    hostname: peer2
  client:
    #register-with-eureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:19081/eureka/
  server:
    enable-self-preservation: false #关闭自我保护模式,默认为开启
    eviction-interval-timer-in-ms: 5000 #扫描失效服务的时间间隔,默认60秒    